name: Commit to another repo using actions/checkout

on:
  push:
    branches:
      - main

jobs:
  commit-other-repo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout other repo
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository_owner }}/actions-commit2
          token: ${{ secrets.OTHER_REPO_PAT }}
          path: actions-commit2

      - name: Commit and push
        env:
          GITHUB_TOKEN: ${{ secrets.OTHER_REPO_PAT }}
        run: |
          cd actions-commit2
          echo "Updated at $(date)" >> update.log
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add update.log
          git commit -m "Update from workflow" || echo "No changes"
          git push
